In [1]:
import pandas as pd
import sqlite3

In [2]:
from google.colab import files

uploaded = files.upload()

Saving cleaned_road_accidents.csv to cleaned_road_accidents.csv

In [3]:

# Step 3: Load Dataset
# Loaded the cleaned CSV file into a Pandas DataFrame.

df = pd.read_csv("cleaned_road_accidents.csv")

print("Shape:", df.shape)

df.head()

Shape: (20000, 26)

,accident_id,city,state,latitude,longitude,date,time,hour,day_of_week,is_weekend,...,traffic_density,cause,accident_severity,vehicles_involved,casualties,is_peak_hour,festival,risk_score,year,month
0,0,Pune,Maharashtra,18.680827,73.930388,2023-10-22,5:00,5,Sunday,1,...,high,weather,fatal,2,2,0,NaN,0.85,2023,October
1,1,Mumbai,Maharashtra,18.817732,72.790846,2023-05-21,4:00,4,Sunday,1,...,low,weather,major,4,3,0,NaN,0.10,2023,May
2,2,Mumbai,Maharashtra,19.096889,72.819424,2024-07-10,13:00,13,Wednesday,0,...,medium,weather,minor,1,1,0,NaN,0.45,2024,July
3,3,Chandigarh,Punjab,30.787805,76.847507,2025-03-30,11:00,11,Sunday,1,...,high,distraction,minor,5,2,0,NaN,0.65,2025,March
4,4,Chennai,Tamil Nadu,12.965155,80.283313,2024-01-25,16:00,16,Thursday,0,...,low,distraction,minor,2,1,0,NaN,0.10,2024,January

In [4]:
# Step 4: Create SQLite Database
# Created a SQLite database and stored the dataset as a table.

conn = sqlite3.connect("road_accidents.db")

df.to_sql(
    "accidents",
    conn,
    if_exists="replace",
    index=False
)

print("Database Created Successfully")

Database Created Successfully

In [5]:
# Step 5: View Table Structure
# Verified the table columns and database schema.
query = """
PRAGMA table_info(accidents);
"""

pd.read_sql(query, conn)

    cid               name     type  notnull dflt_value  pk
0     0        accident_id  INTEGER        0       None   0
1     1               city     TEXT        0       None   0
2     2              state     TEXT        0       None   0
3     3           latitude     REAL        0       None   0
4     4          longitude     REAL        0       None   0
5     5               date     TEXT        0       None   0
6     6               time     TEXT        0       None   0
7     7               hour  INTEGER        0       None   0
8     8        day_of_week     TEXT        0       None   0
9     9         is_weekend  INTEGER        0       None   0
10   10          road_type     TEXT        0       None   0
11   11              lanes  INTEGER        0       None   0
12   12     traffic_signal  INTEGER        0       None   0
13   13            weather     TEXT        0       None   0
14   14         visibility     TEXT        0       None   0
15   15        temperature  INTEGER        0       None   0
16   16    traffic_density     TEXT        0       None   0
17   17              cause     TEXT        0       None   0
18   18  accident_severity     TEXT        0       None   0
19   19  vehicles_involved  INTEGER        0       None   0
20   20         casualties  INTEGER        0       None   0
21   21       is_peak_hour  INTEGER        0       None   0
22   22           festival     TEXT        0       None   0
23   23         risk_score     REAL        0       None   0
24   24               year  INTEGER        0       None   0
25   25              month     TEXT        0       None   0

In [6]:

# Query 1: Total Accidents
# Calculated the total number of accident records.
query = """
SELECT COUNT(*) AS total_accidents
FROM accidents;
"""

pd.read_sql(query, conn)

   total_accidents
0            20000

In [7]:
# Query 2: Top 10 Cities
# Identified the cities with the highest number of accidents.
query = """
SELECT city,
       COUNT(*) AS total_accidents
FROM accidents
GROUP BY city
ORDER BY total_accidents DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

         city  total_accidents
0  Chandigarh             2577
1     Chennai             2575
2     Kolkata             2559
3        Pune             2517
4      Mumbai             2492
5   Bangalore             2438
6       Delhi             2433
7   Hyderabad             2409

In [8]:
# Query 3: State-wise Analysis
# Analyzed accident counts across different states.
query = """
SELECT state,
       COUNT(*) AS total_accidents
FROM accidents
GROUP BY state
ORDER BY total_accidents DESC;
"""

pd.read_sql(query, conn)

         state  total_accidents
0  Maharashtra             5009
1       Punjab             2577
2   Tamil Nadu             2575
3  West Bengal             2559
4    Karnataka             2438
5        Delhi             2433
6    Telangana             2409

In [9]:
# Query 4: Weather Analysis
# Examined the impact of weather conditions on accidents.
query = """
SELECT weather,
       COUNT(*) AS total_accidents
FROM accidents
GROUP BY weather
ORDER BY total_accidents DESC;
"""

pd.read_sql(query, conn)

  weather  total_accidents
0   clear             6690
1    rain             6677
2     fog             6633

In [10]:
# Query 5: Severity Analysis
# Analyzed the distribution of accident severity levels.$0
query = """
SELECT accident_severity,
       COUNT(*) AS total
FROM accidents
GROUP BY accident_severity
ORDER BY total DESC;
"""

pd.read_sql(query, conn)

  accident_severity  total
0             minor  11025
1             major   5988
2             fatal   2987

In [11]:

# Query 6: Weekend Analysis
# Compared accidents occurring on weekends and weekdays.$0
query = """
SELECT is_weekend,
       COUNT(*) AS total
FROM accidents
GROUP BY is_weekend;
"""

pd.read_sql(query, conn)

   is_weekend  total
0           0  14277
1           1   5723

In [12]:
# Query 7: Peak Hour Analysis
# Analyzed accident frequency during peak traffic hours.$0
query = """
SELECT is_peak_hour,
       COUNT(*) AS total
FROM accidents
GROUP BY is_peak_hour;
"""

pd.read_sql(query, conn)

   is_peak_hour  total
0             0  15052
1             1   4948

In [13]:
# Query 8: Traffic Density Analysis
# Studied the relationship between traffic density and accidents.$0
query = """
SELECT traffic_density,
       COUNT(*) AS total_accidents
FROM accidents
GROUP BY traffic_density
ORDER BY total_accidents DESC;
"""

pd.read_sql(query, conn)

  traffic_density  total_accidents
0             low             7067
1            high             7034
2          medium             5899

In [14]:

# Query 9: Average Casualties Analysis
# Calculated average casualties for each severity level.$0
query = """
SELECT accident_severity,
       ROUND(AVG(casualties),2) AS avg_casualties
FROM accidents
GROUP BY accident_severity;
"""

pd.read_sql(query, conn)

  accident_severity  avg_casualties
0             fatal            3.00
1             major            1.49
2             minor            1.51

In [15]:

# Query 10: Risk Score Analysis
# Identified cities with the highest average risk scores.$0
query = """
SELECT city,
       ROUND(AVG(risk_score),2) AS avg_risk_score
FROM accidents
GROUP BY city
ORDER BY avg_risk_score DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

         city  avg_risk_score
0        Pune            0.44
1   Hyderabad            0.44
2       Delhi            0.44
3     Chennai            0.44
4  Chandigarh            0.44
5   Bangalore            0.44
6      Mumbai            0.43
7     Kolkata            0.43

In [16]:
# Query 11: Road Type Analysis
# Examined accident occurrences across different road types.$0
query = """
SELECT road_type,
       COUNT(*) AS total_accidents
FROM accidents
GROUP BY road_type
ORDER BY total_accidents DESC;
"""

pd.read_sql(query, conn)

  road_type  total_accidents
0     urban             6745
1     rural             6639
2   highway             6616

In [17]:
# Query 12: Vehicles Involved Analysis
# Analyzed the number of vehicles involved in accidents.$0
query = """
SELECT vehicles_involved,
       COUNT(*) AS total_accidents
FROM accidents
GROUP BY vehicles_involved
ORDER BY total_accidents DESC;
"""

pd.read_sql(query, conn)

   vehicles_involved  total_accidents
0                  2             4030
1                  1             4030
2                  3             4007
3                  5             3997
4                  4             3936

In [18]:
# Query 13: Monthly Accident Trend
# Studied accident trends across different months.$0
query = """
SELECT month,
       COUNT(*) AS total_accidents
FROM accidents
GROUP BY month
ORDER BY total_accidents DESC;
"""

pd.read_sql(query, conn)

        month  total_accidents
0     January             2044
1       March             2043
2    February             1865
3       April             1763
4         May             1593
5      August             1588
6        July             1543
7    November             1533
8    December             1525
9     October             1516
10       June             1512
11  September             1475

In [19]:
# Query 14: Dangerous Cities Analysis
# Identified cities with the highest casualty counts.$0
query = """
SELECT city,
       SUM(casualties) AS total_casualties
FROM accidents
GROUP BY city
ORDER BY total_casualties DESC
LIMIT 5;
"""

pd.read_sql(query, conn)

         city  total_casualties
0     Chennai              4567
1     Kolkata              4508
2        Pune              4419
3  Chandigarh              4377
4      Mumbai              4297

In [20]:
#Highest Severity Cities
# Analyzed average accident severity across cities.$0
query = """
SELECT city,
       ROUND(AVG(accident_severity),2) AS avg_severity
FROM accidents
GROUP BY city
ORDER BY avg_severity DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

         city  avg_severity
0        Pune           0.0
1      Mumbai           0.0
2     Kolkata           0.0
3   Hyderabad           0.0
4       Delhi           0.0
5     Chennai           0.0
6  Chandigarh           0.0
7   Bangalore           0.0

In [ ]:
print("Task 2 Completed Successfully")
print("SQL Database Created")
print("15 SQL Queries Executed")
print("Road Accident Dataset Successfully Analyzed")

Task 2 Completed Successfully
SQL Database Created
15 SQL Queries Executed
Road Accident Dataset Successfully Analyzed